//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class sumatrain_dbEntities : DbContext
    {
        public sumatrain_dbEntities()
            : base("name=sumatrain_dbEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
