//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Experience { get; set; }
    }
}
